# pylint: skip-file
# Generated by Django 6.0.5 on 2026-05-24 19:44

import django.db.models.deletion
import uuid_utils._uuid_utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Experiment",
            fields=[
                (
                    "experiment_id",
                    models.UUIDField(
                        default=uuid_utils._uuid_utils.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ObservedObject",
            fields=[
                (
                    "observed_object_id",
                    models.UUIDField(
                        default=uuid_utils._uuid_utils.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "observed_object_code",
                    models.CharField(
                        help_text="e.g.: cow 125, building n°2, vehicle 1-xxx xxx, etc.",
                        max_length=64,
                        unique=True,
                        verbose_name="Observed Object Code",
                    ),
                ),
                (
                    "observed_object_extra_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='e.g.: {name: "super cow", sex: "F"}',
                        verbose_name="Observed Object Associated Extra Data",
                    ),
                ),
                ("observed_object_created_at", models.DateTimeField(auto_now_add=True)),
                ("observed_object_updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ExperimentObservedObject",
            fields=[
                (
                    "experiment_observed_object_id",
                    models.UUIDField(
                        default=uuid_utils._uuid_utils.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "experiment_observed_object_created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "experiment_observed_object_experiment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observed_object_links",
                        to="core_data.experiment",
                    ),
                ),
                (
                    "experiment_observed_object_observed_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiment_links",
                        to="core_data.observedobject",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="experiment",
            name="experiment_observed_objects",
            field=models.ManyToManyField(
                related_name="experiment_observed_objects",
                through="core_data.ExperimentObservedObject",
                to="core_data.observedobject",
            ),
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "project_id",
                    models.UUIDField(
                        default=uuid_utils._uuid_utils.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("project_code", models.CharField(max_length=64, unique=True)),
                (
                    "project_primary_owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="primary_owned_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="experiment",
            name="experiment_project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="experiment_projects",
                to="core_data.project",
            ),
        ),
        migrations.CreateModel(
            name="ProjectMembership",
            fields=[
                (
                    "project_membership_id",
                    models.UUIDField(
                        default=uuid_utils._uuid_utils.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "project_membership_role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("advisor", "Advisor"),
                            ("scientist", "Scientist"),
                            ("technician", "Technician"),
                            ("viewer", "Viewer"),
                            ("none", "None"),
                        ],
                        default="none",
                        max_length=16,
                    ),
                ),
                ("project_membership_is_active", models.BooleanField(default=True)),
                (
                    "project_membership_created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                ("project_membership_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project_membership_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="core_data.project",
                    ),
                ),
                (
                    "project_membership_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="project",
            name="project_members",
            field=models.ManyToManyField(
                blank=True,
                related_name="projects",
                through="core_data.ProjectMembership",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="experimentobservedobject",
            constraint=models.UniqueConstraint(
                fields=(
                    "experiment_observed_object_experiment",
                    "experiment_observed_object_observed_object",
                ),
                name="uq_experiment_observed_object",
            ),
        ),
        migrations.AddIndex(
            model_name="projectmembership",
            index=models.Index(
                fields=["project_membership_project", "project_membership_user"],
                name="core_data_p_project_1d089d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="projectmembership",
            index=models.Index(
                fields=["project_membership_project", "project_membership_role"],
                name="core_data_p_project_634519_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectmembership",
            constraint=models.UniqueConstraint(
                fields=("project_membership_project", "project_membership_user"),
                name="uq_project_membership_project_user",
            ),
        ),
    ]
