# pylint: skip-file
# Generated by Django 6.0.5 on 2026-05-24 19:44

import django.db.models.deletion
import uuid_utils._uuid_utils
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GPSRawData",
            fields=[
                (
                    "gps_raw_data_id",
                    models.UUIDField(
                        default=uuid_utils._uuid_utils.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("gps_raw_data_sensors_code", models.CharField(max_length=64)),
                ("gps_raw_data_line_no", models.IntegerField()),
                ("gps_raw_data_utc_date", models.DateField()),
                ("gps_raw_data_utc_time", models.TimeField()),
                ("gps_raw_data_lmt_date", models.DateField()),
                ("gps_raw_data_lmt_time", models.TimeField()),
                ("gps_raw_data_ecef_x", models.IntegerField()),
                ("gps_raw_data_ecef_y", models.IntegerField()),
                ("gps_raw_data_ecef_z", models.IntegerField()),
                ("gps_raw_data_latitude", models.FloatField()),
                ("gps_raw_data_longitude", models.FloatField()),
                ("gps_raw_data_height", models.FloatField()),
                ("gps_raw_data_dop", models.FloatField()),
                ("gps_raw_data_nav", models.CharField(max_length=2)),
                ("gps_raw_data_validated", models.CharField(max_length=3)),
                ("gps_raw_data_sats_used", models.IntegerField()),
                ("gps_raw_data_ch01_sat_id", models.IntegerField()),
                ("gps_raw_data_ch01_sat_cnr", models.IntegerField()),
                ("gps_raw_data_ch02_sat_id", models.IntegerField()),
                ("gps_raw_data_ch02_sat_cnr", models.IntegerField()),
                ("gps_raw_data_ch03_sat_id", models.IntegerField()),
                ("gps_raw_data_ch03_sat_cnr", models.IntegerField()),
                ("gps_raw_data_ch04_sat_id", models.IntegerField()),
                ("gps_raw_data_ch04_sat_cnr", models.IntegerField()),
                ("gps_raw_data_ch05_sat_id", models.IntegerField()),
                ("gps_raw_data_ch05_sat_cnr", models.IntegerField()),
                ("gps_raw_data_ch06_sat_id", models.IntegerField()),
                ("gps_raw_data_ch06_sat_cnr", models.IntegerField()),
                ("gps_raw_data_ch07_sat_id", models.IntegerField()),
                ("gps_raw_data_ch07_sat_cnr", models.IntegerField()),
                ("gps_raw_data_ch08_sat_id", models.IntegerField()),
                ("gps_raw_data_ch08_sat_cnr", models.IntegerField()),
                ("gps_raw_data_ch09_sat_id", models.IntegerField()),
                ("gps_raw_data_ch09_sat_cnr", models.IntegerField()),
                ("gps_raw_data_ch10_sat_id", models.IntegerField()),
                ("gps_raw_data_ch10_sat_cnr", models.IntegerField()),
                ("gps_raw_data_ch11_sat_id", models.IntegerField()),
                ("gps_raw_data_ch11_sat_cnr", models.IntegerField()),
                ("gps_raw_data_ch12_sat_id", models.IntegerField()),
                ("gps_raw_data_ch12_sat_cnr", models.IntegerField()),
                ("gps_raw_data_main_vol", models.FloatField()),
                ("gps_raw_data_bu_vol", models.FloatField()),
                ("gps_raw_data_temp", models.FloatField()),
                ("gps_raw_data_easting", models.IntegerField()),
                ("gps_raw_data_northing", models.IntegerField()),
                ("gps_raw_data_remarks", models.TextField()),
                ("gps_raw_data_created_at", models.DateTimeField(auto_now_add=True)),
                ("gps_raw_data_updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "gps_raw_data",
            },
        ),
        migrations.CreateModel(
            name="GPSSensor",
            fields=[
                (
                    "gps_sensors_id",
                    models.UUIDField(
                        default=uuid_utils._uuid_utils.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "gps_sensors_code",
                    models.CharField(
                        help_text="e.g.: Ulg GPS 12",
                        max_length=64,
                        unique=True,
                        verbose_name="GPS Sensors Code of Identification",
                    ),
                ),
                (
                    "gps_sensor_purchase_date",
                    models.DateField(
                        help_text="e.g.: 2020-07-07",
                        verbose_name="GPS Sensor Purchase Date",
                    ),
                ),
                (
                    "gps_sensor_frequency",
                    models.FloatField(
                        help_text="e.g.: 60",
                        verbose_name="GPS Sensor Sampling Rate (Hz)",
                    ),
                ),
                (
                    "gps_sensor_vendor",
                    models.CharField(
                        blank=True,
                        help_text="e.g.: Globaltek",
                        max_length=128,
                        verbose_name="GPS Sensor Vendor Name",
                    ),
                ),
                (
                    "gps_sensor_model",
                    models.CharField(
                        blank=True,
                        help_text="e.g.: FT203",
                        max_length=128,
                        verbose_name="GPS Sensor Model",
                    ),
                ),
                (
                    "gps_sensor_sim_card",
                    models.CharField(
                        blank=True,
                        help_text="e.g.: 123454564654651654",
                        max_length=64,
                        verbose_name="IEMI Card Number",
                    ),
                ),
                (
                    "gps_sensor_active",
                    models.BooleanField(
                        default=True,
                        help_text="GPS Sensor Status",
                        verbose_name="GPS Sensor Status",
                    ),
                ),
                ("gps_sensor_created_at", models.DateTimeField(auto_now_add=True)),
                ("gps_sensor_updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProcessedGPSDataObservedObject",
            fields=[
                (
                    "processed_gps_data_observed_object_id",
                    models.UUIDField(
                        default=uuid_utils._uuid_utils.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "processed_gps_data_observed_object_uuid",
                    models.UUIDField(
                        help_text="UUID of the observed object managed by the core layer.",
                        verbose_name="Observed Object ID",
                    ),
                ),
                (
                    "processed_gps_data_observed_object_acquisition_time",
                    models.DateTimeField(),
                ),
                ("processed_gps_data_observed_object_longitude", models.FloatField()),
                ("processed_gps_data_observed_object_latitude", models.FloatField()),
                (
                    "processed_gps_data_observed_object_geom",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="GeoJSON point in EPSG:4326.",
                        verbose_name="Processed GPS Geometry",
                    ),
                ),
                (
                    "processed_gps_data_observed_object_insert_timestamp",
                    models.DateTimeField(),
                ),
                (
                    "processed_gps_data_sensors",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gps_sensor_link2",
                        to="gps_data.gpssensor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WildFiGPSFix",
            fields=[
                (
                    "wildfi_gps_fix_id",
                    models.UUIDField(
                        default=uuid_utils._uuid_utils.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("wildfi_device_id", models.CharField(db_index=True, max_length=128)),
                (
                    "observed_object_id",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID of the observed object managed by the core layer.",
                        null=True,
                        verbose_name="Observed Object ID",
                    ),
                ),
                (
                    "dealiot_topic",
                    models.CharField(db_index=True, default="raw.gps", max_length=64),
                ),
                ("source", models.CharField(default="wildfi-mqtt", max_length=64)),
                ("mqtt_topic", models.CharField(blank=True, max_length=255)),
                ("acquisition_time", models.DateTimeField(db_index=True)),
                ("ingested_at", models.DateTimeField(blank=True, null=True)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("altitude", models.FloatField(blank=True, null=True)),
                ("speed", models.FloatField(blank=True, null=True)),
                ("heading", models.FloatField(blank=True, null=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("message_metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["wildfi_device_id", "acquisition_time"],
                        name="gps_data_wi_wildfi__3f5d69_idx",
                    ),
                    models.Index(
                        fields=["dealiot_topic", "acquisition_time"],
                        name="gps_data_wi_dealiot_bdc6e3_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("latitude__gte", -90.0), ("latitude__lte", 90.0)
                        ),
                        name="ck_wildfi_gps_latitude_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("longitude__gte", -180.0), ("longitude__lte", 180.0)
                        ),
                        name="ck_wildfi_gps_longitude_range",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ObservedObjectGPSSensor",
            fields=[
                (
                    "observed_object_gps_sensors_id",
                    models.UUIDField(
                        default=uuid_utils._uuid_utils.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "observed_object_gps_sensor_observed_object_id",
                    models.UUIDField(
                        help_text="UUID of the observed object managed by the core layer.",
                        verbose_name="Observed Object ID",
                    ),
                ),
                ("observed_object_start_time", models.DateTimeField()),
                ("observed_object_end_time", models.DateTimeField()),
                (
                    "observed_object_notes",
                    models.JSONField(
                        default=dict,
                        help_text='e.g.: {"type_of_data": "GPS Data Imported from file"}',
                        verbose_name="GPS Sensor Notes",
                    ),
                ),
                (
                    "observed_object_gps_sensor_gps_sensor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gps_sensor_link",
                        to="gps_data.gpssensor",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "observed_object_start_time__lte",
                                models.F("observed_object_end_time"),
                            )
                        ),
                        name="ck_timestamp_start_before_end",
                    ),
                    models.UniqueConstraint(
                        fields=(
                            "observed_object_gps_sensor_observed_object_id",
                            "observed_object_gps_sensor_gps_sensor",
                            "observed_object_start_time",
                        ),
                        name="uq_obj_sensor_start",
                    ),
                ],
            },
        ),
    ]
