sonar.projectKey=Smartappli_DEALData
sonar.organization=smartappli-github
sonar.projectName=DEALData
sonar.projectVersion=1.0

sonar.sources=dealdata_common,core_layer,gps_layer,sensor_layer,docker-compose.yml,docker-compose.dev.yml,docker-compose.staging.yml,docker-compose.prod.yml,pyproject.toml

sonar.python.version=3.14
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/.venv/**,**/__pycache__/**,**/*.pyc,**/.git/**,**/logs/**,**/node_modules/**,**/migrations/**
sonar.test.inclusions=**/tests.py,**/tests/**/*.py
sonar.coverage.exclusions=dealdata_common/**,**/manage.py,**/*/settings.py,**/*/asgi.py,**/*/wsgi.py,**/admin.py,**/apps.py,**/migrations/**,core_layer/auth/**

sonar.python.coverage.reportPaths=coverage-core.xml,coverage-gps.xml,coverage-sensor.xml
