# pylint: skip-file
# Generated by Django 6.0.5 on 2026-05-24 19:44

import django.db.models.deletion
import uuid_utils._uuid_utils
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sensor",
            fields=[
                (
                    "sensor_id",
                    models.UUIDField(
                        default=uuid_utils._uuid_utils.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sensor_vendor",
                    models.CharField(
                        help_text="Bosch", max_length=32, verbose_name="Vendor"
                    ),
                ),
                (
                    "sensor_model",
                    models.CharField(
                        help_text="BMP 680", max_length=32, verbose_name="Model"
                    ),
                ),
                (
                    "sensor_code",
                    models.CharField(
                        help_text="Sensor n°1",
                        max_length=32,
                        verbose_name="Sensor Code",
                    ),
                ),
                ("sensor_create_at", models.DateTimeField(auto_now_add=True)),
                ("sensor_update_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("sensor_code",), name="uq_sensor_code"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SensorData",
            fields=[
                (
                    "sensor_data_id",
                    models.UUIDField(
                        default=uuid_utils._uuid_utils.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sensor_data_utc_date", models.DateField()),
                ("sensor_data_utc_time", models.TimeField()),
                ("sensor_data_lmt_date", models.DateField()),
                ("sensor_data_lmt_time", models.TimeField()),
                ("sensor_data_value", models.JSONField(default=dict)),
                ("sensor_data_create_at", models.DateTimeField(auto_now_add=True)),
                ("sensor_data_update_at", models.DateTimeField(auto_now=True)),
                (
                    "sensor_data_sensor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sensor_data_sensor",
                        to="sensor_data.sensor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SensorDataObservedObject",
            fields=[
                (
                    "sensor_data_observed_object_id",
                    models.UUIDField(
                        default=uuid_utils._uuid_utils.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sensor_data_observed_object_object_id",
                    models.UUIDField(
                        help_text="UUID of the observed object managed by the core layer.",
                        verbose_name="Observed Object ID",
                    ),
                ),
                (
                    "sensor_data_observed_object_acquisition_time",
                    models.DateTimeField(),
                ),
                ("sensor_data_observed_object_value", models.JSONField(default=dict)),
                (
                    "sensor_data_observed_object_create_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "sensor_data_observed_object_update_at",
                    models.DateTimeField(auto_now=True),
                ),
                (
                    "sensor_data_observed_object_sensor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sensor_data_observed_object_sensor",
                        to="sensor_data.sensor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WildFiDecodedSensorEvent",
            fields=[
                (
                    "wildfi_decoded_sensor_event_id",
                    models.UUIDField(
                        default=uuid_utils._uuid_utils.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("wildfi_device_id", models.CharField(db_index=True, max_length=128)),
                (
                    "observed_object_id",
                    models.UUIDField(
                        blank=True,
                        help_text="UUID of the observed object managed by the core layer.",
                        null=True,
                        verbose_name="Observed Object ID",
                    ),
                ),
                (
                    "dealiot_topic",
                    models.CharField(
                        db_index=True, default="raw.sensor", max_length=64
                    ),
                ),
                ("source", models.CharField(default="wildfi-mqtt", max_length=64)),
                ("mqtt_topic", models.CharField(blank=True, max_length=255)),
                ("acquisition_time", models.DateTimeField(db_index=True)),
                ("ingested_at", models.DateTimeField(blank=True, null=True)),
                ("sensor_type", models.CharField(blank=True, max_length=64)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("message_metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["wildfi_device_id", "acquisition_time"],
                        name="sensor_data_wildfi__ed21f6_idx",
                    ),
                    models.Index(
                        fields=["dealiot_topic", "acquisition_time"],
                        name="sensor_data_dealiot_6036c3_idx",
                    ),
                    models.Index(
                        fields=["sensor_type", "acquisition_time"],
                        name="sensor_data_sensor__d7efa6_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SensorObservedObject",
            fields=[
                (
                    "sensor_observed_object_id",
                    models.UUIDField(
                        default=uuid_utils._uuid_utils.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "sensor_observed_object_object_id",
                    models.UUIDField(
                        help_text="UUID of the observed object managed by the core layer.",
                        verbose_name="Observed Object ID",
                    ),
                ),
                ("sensor_observed_object_start_time", models.TimeField()),
                ("sensor_observed_object_end_time", models.TimeField()),
                ("sensor_observed_object_notes", models.CharField(max_length=255)),
                (
                    "sensor_observed_object_create_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "sensor_observed_object_update_at",
                    models.DateTimeField(auto_now=True),
                ),
                (
                    "sensor_observed_object_sensor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sensor_observed_object_sensor",
                        to="sensor_data.sensor",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "sensor_observed_object_end_time__gte",
                                models.F("sensor_observed_object_start_time"),
                            )
                        ),
                        name="soo_end_time_gte_start_time",
                    )
                ],
            },
        ),
    ]
