# Generated by Django 6.0.5 on 2026-05-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sensor_data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wildfidecodedsensorevent",
            name="event_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Optional upstream DEALIoT/Kafka event identifier.",
                max_length=128,
            ),
        ),
        migrations.AddField(
            model_name="wildfidecodedsensorevent",
            name="message_key",
            field=models.CharField(
                blank=True,
                help_text="Optional Kafka or MQTT key used by DEALIoT.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="wildfidecodedsensorevent",
            name="payload_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Stable SHA-256 hash used for idempotent ingestion.",
                max_length=64,
            ),
        ),
        migrations.AddConstraint(
            model_name="wildfidecodedsensorevent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("event_id", ""), _negated=True),
                fields=("source", "event_id"),
                name="uq_wildfi_sensor_source_event_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="wildfidecodedsensorevent",
            constraint=models.UniqueConstraint(
                condition=models.Q(("payload_hash", ""), _negated=True),
                fields=("source", "payload_hash"),
                name="uq_wildfi_sensor_source_payload_hash",
            ),
        ),
    ]
