# Generated by Django 6.0.5 on 2026-05-24 20:03

import sensor_data.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sensor_data", "0002_wildfidecodedsensorevent_event_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensor",
            name="sensor_id",
            field=models.UUIDField(
                default=sensor_data.models.uuid7_value,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="sensordata",
            name="sensor_data_id",
            field=models.UUIDField(
                default=sensor_data.models.uuid7_value,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="sensordataobservedobject",
            name="sensor_data_observed_object_id",
            field=models.UUIDField(
                default=sensor_data.models.uuid7_value,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="sensorobservedobject",
            name="sensor_observed_object_id",
            field=models.UUIDField(
                default=sensor_data.models.uuid7_value,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="wildfidecodedsensorevent",
            name="wildfi_decoded_sensor_event_id",
            field=models.UUIDField(
                default=sensor_data.models.uuid7_value,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
